import { Profanity } from "@2toad/profanity";

export const PROFANITY_LANGUAGES = [
  "ar",
  "zh",
  "en",
  "fr",
  "de",
  "hi",
  "it",
  "ja",
  "ko",
  "pt",
  "ru",
  "es",
];

export const profanity = new Profanity({
  languages: PROFANITY_LANGUAGES,
  wholeWord: false,     // Check for profane words within larger strings, not just whole words
});

export const WHITELIST_WORDS = [
  // Excluding words from the library's list that are really just common words or have multiple meanings, to reduce false positives
  '5',
  'b1',
  'dl',
  'f4b',
  'no',
  'damn',
  'b',
  '$',
  '$$',
  '·',
  'doosh',
  'duche',
  'hoar',
  'hoare',
  'hoer',
  'jap',
  'kawk',
  'nob',
  'pawn',
  'pecker',
  'poop',
  'prick',
  'screwing',
  't',
  'turd',
  'willies',
  'willy',
  'bum',
  '♪',
  'dyke',
  'esel',
  'ch',
  'flat',
  'p',
  'aw',
  'wa',
  'sh',
  'aus',
  'mo',
  'ya',
  'les',
  'a)',
  'nut',
  'bite',
  'pour',
  'bride',
  'thorax',
  '3 points',
  '4 h',
  'pic',
  'lancer',
  'biga',
  'fava',
  'mona',
  'pippa',
  'porco',
  'regina',
  'sega',
  'p0',
  'paus',
  'bar',
  'bo',

  // Questionable if we should whitelist these
  'gay',
  'idiot',
  'piss',
  'pissed',
  'pisser',
  'pissers',
  'pisses',
  'pissflaps',
  'pissin',
  'pissing',
  'pissoff',
  'shag',
  'spac',
  'tit',    // Results in flagging words like 'petit'
  'toss',
  'tosser',
  'twat',
  'tw4t',
  'wang',   // Also appears in some normal words
  'coon',
  'bastard',
  'hor',    // Appears in words like "horn", "horse", etc.
  'i3',     // Apparently sometimes used as "B" in some words.

  // Excluding some edge cases resulting from 'wholeDWords: false' parameter
  'homosapien',
  'homosapiens',
  'wanky',
  'grass',

  'assess',
  'assessment',
  'assistant',
  'association',
  'assume',
  'assumption',
  'assign',
  'assignment',
  'assembly',
  'assert',
  'assertion',
  'asset',
  'assets',
  'pass',
  'passage',
  'passenger',
  'passion',
  'classic',
  'class',
  'classification',
  'grass',
  'harass',
  'embarrass',

  'arsenal',
  'arsenic',
  'parse',
  'parser',
  'sparse',
  'accumulate',
  'accumulation',
  'cumulative',
  'document',
  'circumstance',
  'circumference',
  'cocktail',
  'peacock',
  'hancock',
  'shamrock',
  'sexton',
  'sussex',
  'middlesex',
  'amusement',
  'faculty',
  'horse',
  'horses',
];
profanity.whitelist.addWords(WHITELIST_WORDS);